# Generated by Django 5.2.6 on 2025-10-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_tile', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
