# Generated by Django 5.0.3 on 2025-10-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_tile',
            new_name='post_title',
        ),
    ]
